# Base build settings
[build]
publish = "public"
command = "echo 'Static site - no build required'"

# Production-specific settings
[context.production]
command = "echo 'Static site - no build required'"
# Environment settings for the production context
environment = { SECRETS_SCAN_OMIT_KEYS = ["AUTH0_CLIENT_ID", "AUTH0_DOMAIN"] }
