[build]
  publish = "public"

[context.production]
  command = "echo 'Static site - no build required'"

# Netlify Identity configuration
[identity]
  # Enable registration by invitation only
  open = false
