# Base build settings
[build]
publish = "public"
command = "echo 'Static site - no build required'"

[build.environment]
NETLIFY_EXCLUDE_SCANNING = "true"

# Production-specific settings
[context.production]
command = "echo 'Static site - no build required'"

[context.production.environment]
SECRETS_SCAN_OMIT_KEYS = '["AUTH0_CLIENT_ID", "AUTH0_DOMAIN"]'
