# Simplified Netlify configuration for Persimmon Intelligence
[build]
command = "./build.sh"
publish = "public"

# Basic SPA redirects - auth will be handled by JavaScript
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
