[build]
publish = "public"

[context.production]
command = "echo 'Static site - no build required'"

# Auth0 client credentials are public and safe to expose in client-side code
# No build-time injection needed - avoiding secrets scanning issues
