# Base build settings for all contexts.
[build]
command = "./build.sh"
publish = "public"

# Specific Edge Function routing.
[[edge_functions]]
path = "/*"
function = "auth-check"
import_map = "import_map.json"
