[build]
publish = "public"

[context.production]
command = "echo 'Static site - no build required'"

# Auth0 configuration will be handled via extension
# Environment variables will be set automatically by Auth0 extension
